version: "3.3"

services:
  web3:
    build: .
    command: python run.py
    restart: unless-stopped
    expose:
      - 5000
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi3.rule=Host(`fastapi3.test-kanal.ru`)"
      - "traefik.http.routers.fastapi3.tls=true"
      - "traefik.http.routers.fastapi3.tls.certresolver=letsencrypt"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
