version: "3.3"

networks:
    traefik:
        external: true

services:
  web:
    build: .
    command: python run.py
    restart: unless-stopped
    expose:
      - 5000
    env_file:
      - .env
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi1.rule=Host(`fastapi1.test-kanal.site`)"
      - "traefik.http.routers.fastapi1.tls=true"
      - "traefik.http.routers.fastapi1.tls.certresolver=letsencrypt"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
