version: "3.3"

services:
  web1:
    build: .
    command: python run.py
    restart: unless-stopped
    expose:
      - 5000
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi2.rule=Host(`fastapi2.test-kanal.ru`)"
      - "traefik.http.routers.fastapi2.tls=true"
      - "traefik.http.routers.fastapi2.tls.certresolver=letsencrypt"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs

  traefik1:
    image: traefik:v2.2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.prod.toml:/etc/traefik/traefik.toml"